# Generated by Django 5.2.8 on 2025-12-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
