# Generated by Django 5.2.8 on 2025-12-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag_remove_document_tags_document_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
