# Generated by Django 5.2.8 on 2025-12-04 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='question',
            field=models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
