# Generated by Django 5.2.8 on 2025-12-04 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_query_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='question',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
